# Generated by Django 5.0.6 on 2024-07-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryuser',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
