# Generated by Django 5.0.6 on 2024-06-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_verifieduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifieduser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
