# Generated by Django 5.0.6 on 2024-06-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_customuser_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('responsibility', models.TextField()),
                ('qualifications', models.TextField()),
                ('job_mode', models.CharField(choices=[('WFH', 'Work From Home'), ('WFO', 'Work From Office'), ('Hybrid', 'Hybrid')], max_length=6)),
                ('vacancy', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
